name: "✍️ ​ ​Missing or Deprecated Career Topics"
description: Help us improve the askovix by suggesting changes
labels: [topic-change]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve the askovix with your suggestions.
  - type: input
    id: url
    attributes:
      label: Askovix URL
      description: Please provide the URL of askovix you are suggesting changes to.
      placeholder: https://careerpath.askovix.com/
    validations:
      required: true
  - type: textarea
    id: roadmap-suggestions
    attributes:
      label: Suggestions
      description: What changes would you like to suggest?
      placeholder: Enter your suggestions here.
    validations:
      required: true
